
public class dice {
	//
	private int dNumSides;
	private int dNum;

	//defined dice has the given number of sides and the number of dice that will be used.
	public dice(int numSides, int numD) {
		numSides = dNumSides;
		numD = dNum;
		
		//work in progress
	}
	
	public int roll(int rollNum){
		
		return (int)(Math.random() * (rollNum + 1) );
		//ensures that rolls are randomly generated by the computer.
	}
	
}
